environment:
    matrix:
        - PYTHON: "C:\\Python27"
          PYTHON_ARCH: "32"

        - PYTHON: "C:\\Python35"
          PYTHON_ARCH: "32"

install:
    - "%PYTHON%\\python -m pip install ."
    - "%PYTHON%\\python -m pip install -r requirements.txt"
    - "%PYTHON%\\python -m pip install -r requirements-dev.txt"
    - "set PATH=%PYTHON%\\Scripts\\;%PATH%"

build: false

test_script:
    - set SWAK_EXE_DIR=%APPVEYOR_BUILD_FOLDER%\swak
    - swak list
    - coverage run --source swak --parallel-mode --module pytest tests
    - "tools\\build.bat"

after_test:
    - "%PYTHON%\\python -m pip install codecov"
    - coverage combine .
    - codecov

notifications:
    - provider: Email
      on_build_success: false
      on_build_failure: false
      on_build_status_changed: true
