environment:
    matrix:
        - PYTHON: "C:\\Python27"
        - PYTHON: "C:\\Python35"

install:
    - "%PYTHON%\\python.exe -m pip install tox"
    - "%PYTHON%\\python.exe -m pip install codecov"
    - "%PYTHON%\\python.exe -m pip install pyinstaller"
      # - "SET PATH=%PYTHON\\Scripts\\;%PATH%"

build: false

test_script:
    - dir "%PYTHON%\\Scripts"
    - "%PYTHON%\\python.exe -m tox"

after_test:
    - codecov
