environment:
    matrix:
        - PYTHON: "C:\\Python27"
          PYTHON_ARCH: "32"

        - PYTHON: "C:\\Python35"
          PYTHON_ARCH: "32"

install:
    - "%PYTHON%\\python -m pip install -r requirements.txt"
    - "%PYTHON%\\python -m pip install -r requirements-dev.txt"
    - "set PATH=%PYTHON%\\Scripts\\;%PATH%"

build: false

test_script:
<<<<<<< HEAD
    - "%PYTHON%\\python.exe -m tox"

after_test:
    - "set PATH=%PYTHON%\\Scripts\\;%PATH%"
    - coverage run --source swak -p -m pytest tests
    - build.bat

after_test:
    - "%PYTHON%\\python -m pip install codecov"
    - coverage combine .
