environment:
    matrix:
        - PYTHON: "C:\\Python27"
        - PYTHON: "C:\\Python35"

install:
    - "%PYTHON%\\python.exe -m pip install tox"
    - "%PYTHON%\\python.exe -m pip install codecov"
    - "%PYTHON%\\python.exe -m pip install pyinstaller"

build: false

test_script:
    - dir "%PYTHON%\\Scripts"
    - "%PYTHON%\\python.exe -m tox"

after_test:
    - dir "%PYTHON%\\Scripts"
    - "set PATH=%PYTHON%\\Scripts\\;%PATH%"
    - codecov
