environment:
    matrix:
        - PYTHON: "C:\\Python27"
          PYTHON_ARCH: "32"

        - PYTHON: "C:\\Python35"
          PYTHON_ARCH: "32"

install:
    - "%PYTHON%\\python pip install -r requirements.txt"
    - "%PYTHON%\\python pip install -r requirements-dev.txt"
    - "%PYTHON%\\python pip install codecov"
    - "set PATH=%PYTHON%\\Scripts\\;%PATH%"

build: false

test_script:
    - coverage run --source swak -m pytest tests
    - build.bat

after_test:
    - codecov
