environment:
    global:
        CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"

    matrix:
        - PYTHON: "C:\\Python27"
          PYTHON_ARCH: "32"

        - PYTHON: "C:\\Python35"
          PYTHON_ARCH: "32"

install:
    - "%CMD_IN_ENV% pip install -r requiresments.txt"
    - "%CMD_IN_ENV% pip install -r requiresments-dev.txt"
    - "%CMD_IN_ENV% pip install codecov"

build: false

test_script:
    - "%CMD_IN_ENV% coverage run --source swak -m pytest tests"
    - build.bat

after_test:
    # - "set PATH=%PYTHON%\\Scripts\\;%PATH%"
    - codecov
