language: python

python:
    - "2.7"
    - "3.5"

install:
    - pip install tox-travis
    #- pip install -e .
    #- pip install -r requirements.txt
    #- pip install -r requirements-dev.txt

env:
    - TOX_ENV=py27
    - TOX_ENV=py35
    #global:
        #- SWAK_HOME=$TRAVIS_BUILD_DIR/devhome
        #- SWAK_EXE_DIR=$TRAVIS_BUILD_DIR/swak

script:
    - tox -e $TOX_ENV
    #- coverage run --source swak --module pytest tests -s
    #- ./tools/build.sh

#after_success:
    #- pip install codecov
    #- coverage combine .
    #- codecov

notifications:
    email: false
