language: python

python:
    - "2.7"
    - "3.5"

install:
    - pip install .
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt

env:
    global:
        - SWAK_HOME=$TRAVIS_BUILD_DIR/devhome
        - SWAK_EXE_DIR=$TRAVIS_BUILD_DIR/swak

script:
    - echo $SWAK_EXE_DIR
    - ls -alh $SWAK_EXE_DIR/*
    - cat $SWAK_EXE_DIR/__init__.py
    - coverage run --source swak --module pytest tests
    - ./tools/build.sh

after_success:
    - pip install codecov
    - coverage combine .
    - codecov

notifications:
    email: false
