language: python

python:
    - "2.7"
    - "3.5"

virtualenv:
      system_site_packages: true

install:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt

env:
    global:
        - SWAK_HOME=$TRAVIS_BUILD_DIR/devhome
        - SWAK_EXE_DIR=$TRAVIS_BUILD_DIR/swak

script:
    - coverage run --source swak --module pytest tests -s
    - ./tools/build.sh

after_success:
    - pip install codecov
    - coverage combine .
    - codecov

notifications:
    email: false
