language: python

python:
    - "2.7"
    - "3.5"

install:
    - pip install .
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt

env:
    global:
        - SWAK_HOME=$TRAVIS_BUILD_DIR/devhome

script:
    - coverage run --source swak --parallel-mode --module pytest tests
    - ./build.sh

after_success:
    - pip install codecov
    - coverage combine .
    - codecov

notifications:
    email: false
