environment:
    matrix:
        - PYTHON: "C:\\Python27"
        - PYTHON: "C:\\Python35"

install:
    - "%PYTHON%\\python.exe -m pip install tox"

build: false

test_script:
    - set SWAK_HOME=%APPVEYOR_BUILD_FOLDER%\\devhome
    - "%PYTHON%\\python.exe -m tox"
    
